# Generated by Django 5.0.1 on 2025-01-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=15)),
                ('ProductDescription', models.TextField()),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
