# Generated by Django 5.0.1 on 2024-12-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='errorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=22)),
                ('number', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
