# Generated by Django 5.0.1 on 2024-12-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testappln', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='errorForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('number', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='errorReport',
        ),
    ]
