# Generated by Django 5.0.1 on 2024-12-31 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testappln', '0002_errorform_delete_errorreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpagemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='errorForm',
        ),
    ]
