# Generated by Django 5.0.1 on 2025-01-02 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testappln', '0003_fpagemodel_delete_errorform'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25, validators=[django.core.validators.EmailValidator()])),
                ('password', models.CharField(max_length=12)),
                ('confirm_password', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='fpagemodel',
        ),
    ]
